# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 385)
        MainWindow.setStyleSheet("background-color: rgb(39, 39, 39);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkbox_autorun = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_autorun.setGeometry(QtCore.QRect(350, 320, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkbox_autorun.setFont(font)
        self.checkbox_autorun.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkbox_autorun.setObjectName("checkbox_autorun")
        self.btn_startstop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_startstop.setGeometry(QtCore.QRect(350, 290, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_startstop.setFont(font)
        self.btn_startstop.setStyleSheet("color: rgb(0, 255, 0);\n"
"background-color: rgb(144, 144, 144);")
        self.btn_startstop.setObjectName("btn_startstop")
        self.list_commitments = QtWidgets.QListWidget(self.centralwidget)
        self.list_commitments.setGeometry(QtCore.QRect(10, 80, 361, 201))
        self.list_commitments.setStyleSheet("background-color:rgb(65, 65, 65);\n"
"color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color:rgb(138, 138, 138);  \n"
"alternate-background-color:  rgb(106, 106, 106);")
        self.list_commitments.setObjectName("list_commitments")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(430, 290, 75, 23))
        self.btn_delete.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(144, 144, 144);")
        self.btn_delete.setObjectName("btn_delete")
        self.title_agents = QtWidgets.QLabel(self.centralwidget)
        self.title_agents.setGeometry(QtCore.QRect(220, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.title_agents.setFont(font)
        self.title_agents.setStyleSheet("color: rgb(255, 255, 255);")
        self.title_agents.setObjectName("title_agents")
        self.num_commits = QtWidgets.QLCDNumber(self.centralwidget)
        self.num_commits.setGeometry(QtCore.QRect(70, 10, 81, 23))
        self.num_commits.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.num_commits.setAutoFillBackground(False)
        self.num_commits.setStyleSheet("QLCDNumber{\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: rgb(0, 0, 0)\n"
"}\n"
"")
        self.num_commits.setObjectName("num_commits")
        self.num_agents = QtWidgets.QLCDNumber(self.centralwidget)
        self.num_agents.setGeometry(QtCore.QRect(220, 10, 81, 23))
        self.num_agents.setStyleSheet("QLCDNumber{\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: rgb(0, 0, 0)\n"
"}\n"
"")
        self.num_agents.setObjectName("num_agents")
        self.title_commits = QtWidgets.QLabel(self.centralwidget)
        self.title_commits.setGeometry(QtCore.QRect(60, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.title_commits.setFont(font)
        self.title_commits.setStyleSheet("color: rgb(255, 255, 255);")
        self.title_commits.setObjectName("title_commits")
        self.num_queue = QtWidgets.QLCDNumber(self.centralwidget)
        self.num_queue.setGeometry(QtCore.QRect(370, 10, 81, 23))
        self.num_queue.setStyleSheet("QLCDNumber{\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: rgb(0, 0, 0)\n"
"}\n"
"")
        self.num_queue.setObjectName("num_queue")
        self.queue_title = QtWidgets.QLabel(self.centralwidget)
        self.queue_title.setGeometry(QtCore.QRect(390, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.queue_title.setFont(font)
        self.queue_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.queue_title.setObjectName("queue_title")
        self.label_delete_alert = QtWidgets.QLabel(self.centralwidget)
        self.label_delete_alert.setGeometry(QtCore.QRect(440, 310, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_delete_alert.setFont(font)
        self.label_delete_alert.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_delete_alert.setText("")
        self.label_delete_alert.setObjectName("label_delete_alert")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(390, 290, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_stop.setFont(font)
        self.btn_stop.setStyleSheet("color: rgb(255, 0, 0);background-color: rgb(144, 144, 144);")
        self.btn_stop.setObjectName("btn_stop")
        self.label_update = QtWidgets.QLabel(self.centralwidget)
        self.label_update.setGeometry(QtCore.QRect(20, 290, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_update.setFont(font)
        self.label_update.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_update.setObjectName("label_update")
        self.label_update_time = QtWidgets.QLabel(self.centralwidget)
        self.label_update_time.setGeometry(QtCore.QRect(90, 290, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_update_time.setFont(font)
        self.label_update_time.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_update_time.setText("")
        self.label_update_time.setObjectName("label_update_time")
        self.list_agents = QtWidgets.QListWidget(self.centralwidget)
        self.list_agents.setGeometry(QtCore.QRect(380, 80, 131, 201))
        self.list_agents.setStyleSheet("background-color:rgb(65, 65, 65);\n"
"color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color:rgb(138, 138, 138);  \n"
"alternate-background-color:  rgb(106, 106, 106);")
        self.list_agents.setObjectName("list_agents")
        self.label_alert = QtWidgets.QLabel(self.centralwidget)
        self.label_alert.setGeometry(QtCore.QRect(20, 320, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_alert.setFont(font)
        self.label_alert.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_alert.setText("")
        self.label_alert.setObjectName("label_alert")
        self.queue_title_2 = QtWidgets.QLabel(self.centralwidget)
        self.queue_title_2.setGeometry(QtCore.QRect(10, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.queue_title_2.setFont(font)
        self.queue_title_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(0, 0, 0, 0));")
        self.queue_title_2.setObjectName("queue_title_2")
        self.queue_title_3 = QtWidgets.QLabel(self.centralwidget)
        self.queue_title_3.setGeometry(QtCore.QRect(380, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.queue_title_3.setFont(font)
        self.queue_title_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(0, 0, 0, 0));")
        self.queue_title_3.setObjectName("queue_title_3")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(250, 290, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.btn_pulse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pulse.setGeometry(QtCore.QRect(310, 290, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_pulse.setFont(font)
        self.btn_pulse.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(144, 144, 144);")
        self.btn_pulse.setObjectName("btn_pulse")
        self.checkbox_autorun.raise_()
        self.list_commitments.raise_()
        self.title_agents.raise_()
        self.title_commits.raise_()
        self.queue_title.raise_()
        self.label_delete_alert.raise_()
        self.num_queue.raise_()
        self.num_agents.raise_()
        self.num_commits.raise_()
        self.btn_delete.raise_()
        self.btn_stop.raise_()
        self.label_update.raise_()
        self.label_update_time.raise_()
        self.list_agents.raise_()
        self.label_alert.raise_()
        self.queue_title_2.raise_()
        self.queue_title_3.raise_()
        self.label_status.raise_()
        self.btn_startstop.raise_()
        self.btn_pulse.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 521, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkbox_autorun.setText(_translate("MainWindow", "Autorun"))
        self.btn_startstop.setText(_translate("MainWindow", "►"))
        self.btn_delete.setText(_translate("MainWindow", "Delete"))
        self.title_agents.setText(_translate("MainWindow", "Agents Available"))
        self.title_commits.setText(_translate("MainWindow", "Commits Created"))
        self.queue_title.setText(_translate("MainWindow", "Queue"))
        self.btn_stop.setText(_translate("MainWindow", "■"))
        self.label_update.setText(_translate("MainWindow", "Last Update:"))
        self.queue_title_2.setText(_translate("MainWindow", "Queue"))
        self.queue_title_3.setText(_translate("MainWindow", "Support"))
        self.btn_pulse.setText(_translate("MainWindow", "⦿"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
