# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiassist.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 385)
        MainWindow.setStyleSheet("background-color: rgb(39, 39, 39);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_commitments = QtWidgets.QListWidget(self.centralwidget)
        self.list_commitments.setGeometry(QtCore.QRect(10, 80, 361, 201))
        self.list_commitments.setStyleSheet("background-color:rgb(65, 65, 65);\n"
"color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color:rgb(138, 138, 138);  \n"
"alternate-background-color:  rgb(106, 106, 106);")
        self.list_commitments.setObjectName("list_commitments")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(430, 290, 75, 23))
        self.btn_delete.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(144, 144, 144);")
        self.btn_delete.setObjectName("btn_delete")
        self.title_agents = QtWidgets.QLabel(self.centralwidget)
        self.title_agents.setGeometry(QtCore.QRect(220, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.title_agents.setFont(font)
        self.title_agents.setStyleSheet("color: rgb(255, 255, 255);")
        self.title_agents.setObjectName("title_agents")
        self.num_agents = QtWidgets.QLCDNumber(self.centralwidget)
        self.num_agents.setGeometry(QtCore.QRect(220, 20, 81, 23))
        self.num_agents.setStyleSheet("QLCDNumber{\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: rgb(0, 0, 0)\n"
"}\n"
"")
        self.num_agents.setObjectName("num_agents")
        self.num_queue = QtWidgets.QLCDNumber(self.centralwidget)
        self.num_queue.setGeometry(QtCore.QRect(370, 20, 81, 23))
        self.num_queue.setStyleSheet("QLCDNumber{\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: rgb(0, 0, 0)\n"
"}\n"
"")
        self.num_queue.setObjectName("num_queue")
        self.queue_title = QtWidgets.QLabel(self.centralwidget)
        self.queue_title.setGeometry(QtCore.QRect(390, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.queue_title.setFont(font)
        self.queue_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.queue_title.setObjectName("queue_title")
        self.label_delete_alert = QtWidgets.QLabel(self.centralwidget)
        self.label_delete_alert.setGeometry(QtCore.QRect(440, 310, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_delete_alert.setFont(font)
        self.label_delete_alert.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_delete_alert.setText("")
        self.label_delete_alert.setObjectName("label_delete_alert")
        self.label_update = QtWidgets.QLabel(self.centralwidget)
        self.label_update.setGeometry(QtCore.QRect(20, 290, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_update.setFont(font)
        self.label_update.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_update.setObjectName("label_update")
        self.label_update_time = QtWidgets.QLabel(self.centralwidget)
        self.label_update_time.setGeometry(QtCore.QRect(90, 290, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_update_time.setFont(font)
        self.label_update_time.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_update_time.setText("")
        self.label_update_time.setObjectName("label_update_time")
        self.list_agents = QtWidgets.QListWidget(self.centralwidget)
        self.list_agents.setGeometry(QtCore.QRect(380, 80, 131, 201))
        self.list_agents.setStyleSheet("background-color:rgb(65, 65, 65);\n"
"color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color:rgb(138, 138, 138);  \n"
"alternate-background-color:  rgb(106, 106, 106);")
        self.list_agents.setObjectName("list_agents")
        self.list_commitments.raise_()
        self.title_agents.raise_()
        self.queue_title.raise_()
        self.label_delete_alert.raise_()
        self.num_queue.raise_()
        self.num_agents.raise_()
        self.btn_delete.raise_()
        self.label_update.raise_()
        self.label_update_time.raise_()
        self.list_agents.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 521, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_delete.setText(_translate("MainWindow", "Delete"))
        self.title_agents.setText(_translate("MainWindow", "Agents Available"))
        self.queue_title.setText(_translate("MainWindow", "Queue"))
        self.label_update.setText(_translate("MainWindow", "Last Update:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
